routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
// Route::get('/tampilan', function () {
//     return view('layouts.backend');
// });

Auth::routes(['verify'=>true]);
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/laporan','HomeController@cetak')->name('laporan');
Route::group(['middleware'=>'auth'], function() {
Route::get('/api/datatable/siswa','SiswaController@dataTable')->name('api.datatable.siswa');
Route::get('/api/datatable/pelanggaran','PelanggaranController@data')->name('api.datatable.pelanggaran');
Route::get('/api/datatable/penilaian','PenilaianController@data')->name('api.datatable.penilaian');
Route::resource('siswa', 'SiswaController');
Route::resource('pelanggaran', 'PelanggaranController');
Route::resource('penilaian', 'PenilaianController');

});

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    protected $fillable=[
        'nama','alamat','nis',
    ];

    public function penilaian()
    {
        return $this->hasMany(Penilaian::class,'id_siswa');
    }

}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Siswa;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('siswa.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('siswa.createcopy');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
              'nama'   => 'required|string|min:3',
              'nis'    => 'required|unique:siswas|max:10',
              'alamat' => 'required',
        ]);
        Siswa::create($request->all());
        return redirect()->route('siswa.index')
                         ->with('sukses','berhasil memasukan data');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function show(Siswa $siswa)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function edit(Siswa $siswa)
    {
        $siswa=Siswa::findOrFail($siswa)->first();
        return view('siswa.edit',compact('siswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Siswa $siswa)
    {
        $siswa=Siswa::findOrFail($siswa)->first();
        $this->validate($request,[
            'nama'   => 'required|string|min:3',
            'nis'    => 'required|max:10',
            'alamat' => 'required',
      ]);
       $siswa->update($request->all());
       return redirect()->route('siswa.index')
                         ->with('edit','berhasil edit data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function destroy(Siswa $siswa)
    {
        $siswa=Siswa::findOrFail($siswa)->first();
        $siswa->delete();
        return redirect()->route('siswa.index')
                         ->with('hapus','berhasil hapus data');

    }

    public function dataTable()
    {
        $siswa=Siswa::query();
        return Datatables::of($siswa)
        ->addIndexColumn()
        ->addColumn('action',function($siswa){
            return view('layouts.button',[
                'model'=>$siswa,
                'edit'=>route('siswa.edit',$siswa->id),
                'hapus'=>route('siswa.destroy',$siswa->id)
            ]);
        })
        ->make(true);
     }
}

resources/views/siswa/_form.blade.php
<div class="form-group">
      <label for="squareInput">Nama</label>

      {!! Form::text('nama',null,['class'=>$errors->has('nama') ? 'form-control is-invalid' : 'form-control','required','autofocus','placeholder'=>'nama']) !!}
      @if ($errors->has('nama'))
      <span class="invalid-feedback">
          <strong>{{ $errors->first('nama') }}</strong>
      </span>
     @endif
 </div>
 <div class="form-group">
        <label for="squareInput">Alamat</label>
        {!! Form::textarea('alamat',null,['class'=>$errors->has('alamat') ? 'form-control is-invalid' : 'form-control','required','autofocus','placeholder'=>'alamat']) !!}
        @if ($errors->has('alamat'))
        <span class="invalid-feedback">
            <strong>{{ $errors->first('alamat') }}</strong>
        </span>
       @endif
</div>
<div class="form-group">
        <label for="squareInput">Nis</label>
       {!! Form::number('nis',null,['class'=>$errors->has('nis') ? 'form-control is-invalid' : 'form-control','required','autofocus','placeholder'=>'nis']) !!}
        @if ($errors->has('nis'))
        <span class="invalid-feedback">
            <strong>{{ $errors->first('nis') }}</strong>
        </span>
       @endif
</div>
<div class="form-group">
        <label for="squareInput">Foto</label>
        <br>
        <span class="input-group-btn">
                <a id="lfm" data-input="foto" data-preview="holder" class="btn btn-primary text-white">
                    <i class="fa fa-cloud-upload"></i> Choose
                </a>
            </span>
            {!! Form::text('foto', null, ['id' => 'foto', 'class' => 'form-control', 'readonly']) !!}
            <!-- if -->
            <!-- <img src="#" id="holder" style="margin-top:15px;max-height:254px;max-width: 152px;"> -->
            <!-- endif -->
            <img id="holder" style="margin-top:15px;max-height:254px;max-width: 152px;">
</div>

@section('assets-bottom')
<script src="{{ asset('vendor/laravel-filemanager/js/lfm.js') }}"></script>
<script>
    $(document).ready( function () {
        $('#lfm').filemanager('image');
    });
</script>
@endsection

resources/views/siswa/_formcopy.blade.php
<div class="form-group">
    <label for="squareInput">Nama</label>

    {!! Form::text('nama',null,['class'=>$errors->has('nama') ? 'form-control is-invalid' : 'form-control','required','autofocus','placeholder'=>'nama']) !!}
    @if ($errors->has('nama'))
    <span class="invalid-feedback">
        <strong>{{ $errors->first('nama') }}</strong>
    </span>
   @endif
</div>
<div class="form-group">
      <label for="squareInput">Alamat</label>
      {!! Form::textarea('alamat',null,['class'=>$errors->has('alamat') ? 'form-control is-invalid' : 'form-control','required','autofocus','placeholder'=>'alamat']) !!}
      @if ($errors->has('alamat'))
      <span class="invalid-feedback">
          <strong>{{ $errors->first('alamat') }}</strong>
      </span>
     @endif
</div>
<div class="form-group">
      <label for="squareInput">Nis</label>
     {!! Form::number('nis',null,['class'=>$errors->has('nis') ? 'form-control is-invalid' : 'form-control','required','autofocus','placeholder'=>'nis']) !!}
      @if ($errors->has('nis'))
      <span class="invalid-feedback">
          <strong>{{ $errors->first('nis') }}</strong>
      </span>
     @endif
</div>

@section('assets-bottom')
<script src="{{ asset('vendor/laravel-filemanager/js/lfm.js') }}"></script>
<script>
  $(document).ready( function () {
      $('#lfm').filemanager('image');
  });
</script>
@endsection

resources/views/siswa/create.blade.php
@extends('layouts.backend')
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="card-title">Form</div>
        </div>
        <div class="card-body">
            {!! Form::open(['route'=>'siswa.store','method'=>'POST']) !!}

            @include('siswa._formcopy')


        </div>
        <div class="card-action">
            <button type="submit" name="submit" class="btn btn-success">Submit</button>
            <a href="{{ route('siswa.index') }}" class="btn btn-danger">Cancel</a>
        </div>
        {!! Form::close() !!}

    </div>
</div>
@endsection

resources/views/siswa/createcopy.blade.php
@extends('layouts.backend')
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="card-title">Form</div>
        </div>
        <div class="card-body">
            {!! Form::open(['route'=>'siswa.store','method'=>'POST']) !!}

            @include('siswa._formcopy')


        </div>
        <div class="card-action">
            <button type="submit" name="submit" class="btn btn-success">Submit</button>
            <a href="{{ route('siswa.index') }}" class="btn btn-danger">Cancel</a>
        </div>
        {!! Form::close() !!}

    </div>
</div>
@endsection

resources/views/siswa/edit.blade.php
@extends('layouts.backend')
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="card-title">Form Control Styles</div>
        </div>
        <div class="card-body">
        {!! Form::model($siswa,['route' => ['siswa.update', $siswa->id],'method'=>'PUT']) !!}
             @include('siswa._formcopy')
       </div>
        <div class="card-action">
            <button type="submit" name="submit" class="btn btn-success">Submit</button>
            <a href="{{ route('siswa.index') }}" class="btn btn-danger">Cancel</a>
        </div>
        {!! Form::close() !!}

    </div>
</div>
@endsection

resources/views/siswa/index.blade.php
@extends('layouts.backend')
@section('assets-top')

<link href="{{ asset('datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ asset('datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
@endsection
@section('content')
<div class="card">
    <div class="card-header">
        <div class="card-title">Data Siswa</div>
        @if (session('sukses'))
        <div class="alert alert-info">
          {{ session('sukses') }}
        </div>
        @elseif (session('edit'))
        <div class="alert alert-warning">
                {{ session('edit') }}
              </div>
        @elseif (session('hapus'))
        <div class="alert alert-danger">
                {{ session('hapus') }}
              </div>
       @endif

    </div>
    <div class="card-body">
        <div class="card-sub">
           <a href="{{ route('siswa.create')}}" class="btn btn-danger btn-sm">Tambah data</a>
        </div>
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Alamat</th>
                <th>Nis</th>
                <th></th>
              </tr>
            </thead>
            <tfoot>
               <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Alamat</th>
                <th>Nis</th>
                <th></th>
              </tr>
            </tfoot>
            <tbody>

            </tbody>
          </table>
@endsection
@section('assets-bottom')
    <!-- Page level plugin JavaScript-->
    <script src="{{ asset('datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('datatables/dataTables.bootstrap4.min.js') }}"></script>
    <!-- Responsive examples -->
    <script src="{{ asset('datatables/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('datatables/responsive.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $("#dataTable").DataTable({
                processing :true,
                serverSide :true,
                ajax       :"{{ route('api.datatable.siswa') }}",
                columns:[
                    {data: 'DT_Row_Index',orderable: false, searchable: false},
                    {data: 'nama',      name: 'nama' },
                    {data: 'alamat',    name: 'alamat' },
                    {data: 'nis',       name: 'nis' },
                    {data: 'action',    name: 'action', orderable:false, seacrhable:false},
              ]
            })
        });
    </script>
@endsection