routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
// Route::get('/tampilan', function () {
//     return view('layouts.backend');
// });

Auth::routes(['verify'=>true]);
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/laporan','HomeController@cetak')->name('laporan');
Route::group(['middleware'=>'auth'], function() {
Route::get('/api/datatable/siswa','SiswaController@dataTable')->name('api.datatable.siswa');
Route::get('/api/datatable/pelanggaran','PelanggaranController@data')->name('api.datatable.pelanggaran');
Route::get('/api/datatable/penilaian','PenilaianController@data')->name('api.datatable.penilaian');
Route::resource('siswa', 'SiswaController');
Route::resource('pelanggaran', 'PelanggaranController');
Route::resource('penilaian', 'PenilaianController');

});

resources/views/layouts/backend.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>Ready Bootstrap Dashboard</title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
        <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css' )}}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
        <link rel="stylesheet" href="{{ asset('css/ready.css') }}">
        <link rel="stylesheet" href="{{ asset('css/demo.css')  }}">
        @yield('assets-top')
    </head>
    <body>
        <div class="wrapper">
            <div class="main-header">
                <div class="logo-header">
                    <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <button class="topbar-toggler more"><i class="la la-ellipsis-v"></i></button>
                </div>
                <nav class="navbar navbar-header navbar-expand-lg">
                    <div class="container-fluid">
                        <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                            <li class="nav-item dropdown hidden-caret">
                                <ul class="dropdown-menu notif-box" aria-labelledby="navbarDropdown">
                                    <li>
                                        <div class="notif-center">
                                            <a href="#">
                                                <div class="notif-img">
                                                    <img src="{{ asset('img/profile2.jpg' )}}" alt="Img Profile">
                                                </div>
                                                <div class="notif-content">
                                                    <span class="block">
                                                        Reza send messages to you
                                                    </span>
                                                    <span class="time">12 minutes ago</span>
                                                </div>
                                            </a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false"> <img src="{{ asset('img/profile.jpg' )}}" alt="user-img" width="36" class="img-circle"><span>{{ Auth::user()->name }}</span></span> </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li>
                                        <div class="user-box">
                                            <div class="u-img"><img src="{{ asset('img/profile.jpg' )}}" alt="user"></div>
                                            <div class="u-text">
                                                <h4>{{ Auth::user()->name }}</h4>
                                                <p class="text-muted">{{ Auth::user()->email }}</p></div>
                                        </div>
                                    </li>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                               document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}<i class="fa fa-power-off"></i></a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>

                                </ul>
                                <!-- /.dropdown-user -->
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
            <div class="sidebar">
                <div class="scrollbar-inner sidebar-wrapper">
                    <div class="user">
                        <div class="photo">
                            <img src="{{ asset('img/profile.jpg' )}}">
                        </div>
                        <div class="info">
                            <a class="" data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                                <span>
                                    {{ Auth::user()->name }}
                                </span>
                            </a>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    @include('layouts.menu')
                </div>
            </div>
            <div class="main-panel">
                <div class="content">
                    <div class="container-fluid">
                       @yield('content')
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
</body>
<script src="{{ asset('js/core/jquery.3.2.1.min.js' )}}"></script>
<script src="{{ asset('js/core/bootstrap.min.js' )}}"></script>
@yield('assets-bottom')
@yield('card')
<script src="{{ asset('js/ready.min.js' )}}"></script>
</html>

resources/views/layouts/button.blade.php
{!! Form::model($model, ['url'=>[$hapus],'method'=>'DELETE']) !!}
<a href="{{ $edit }}" class="btn btn-sm btn-outline-secondary" style="padding-bottom: 0px; padding-top: 0px;">
        Edit
<span class="btn-label btn-label-right"><i class="fa fa-edit"></i></span>
</a>
    <button
        type="submit" class="btn btn-sm btn-outline-danger"
        style="padding-bottom: 0px; padding-top: 0px;"
        onclick="return confirm('Apakah Anda Yakin Ingin Menghapus?');"
    >
        Hapus
        <span class="btn-label btn-label-right"><i class="fa fa-trash"></i></span>
</button>
{!! Form::close() !!}

resources/views/layouts/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="http://www.themekita.com">
                        ThemeKita
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Help
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Licenses
                    </a>
                </li>
            </ul>
        </nav>
        <div class="copyright ml-auto">
            2018, made with <i class="la la-heart heart text-danger"></i> by <a href="http://www.themekita.com">ThemeKita</a>
        </div>
    </div>
</footer>

resources/views/layouts/menu.blade.php
<ul class="nav">
    <li class="nav-item active">
        <a href="{{ route('home') }}">
            <i class="la la-dashboard"></i>
            <p>Dashboard</p>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{ route('siswa.index') }}">
            <i class="la la-table"></i>
            <p>Siswa</p>
            <span class="badge badge-count">{{ App\Siswa::count() }}</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{ route('pelanggaran.index') }}">
            <i class="la la-keyboard-o"></i>
            <p>Pelanggaran</p>
            <span class="badge badge-count">{{ App\Pelanggaran::count() }}</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{ route('penilaian.index') }}">
            <i class="la la-th"></i>
            <p>Penilaian</p>
            <span class="badge badge-count">{{ App\Penilaian::count() }}</span>
        </a>
    </li>
</ul>